# Nathanael Gandhi | github.com/NathanaelGandhi

# NOTE: This only works when there are no required status checks
# NOTE: You also need to enable Allow GitHub Actions to create and approve pull requests under Settings > Actions in your repository

name: 'Release Caller'
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  release-conventional-changelog:
    uses: NathanaelGandhi/release-reusable-workflow/.github/workflows/release-reusable.yaml@main
    secrets:
      caller_token: ${{ secrets.GITHUB_TOKEN }}
